"""add search_history table

Revision ID: 8f176cd0f2c3
Revises: feb3261dff71
Create Date: 2026-05-31 14:41:57.721048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f176cd0f2c3'
down_revision: Union[str, None] = 'feb3261dff71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('results_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_from', sa.String(), nullable=True),
    sa.Column('date_to', sa.String(), nullable=True),
    sa.Column('sources_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    # ### end Alembic commands ###
