"""add author_phone and source_title to matches

Revision ID: feb3261dff71
Revises: 40eec1359c5b
Create Date: 2026-05-31 14:21:10.693454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb3261dff71'
down_revision: Union[str, None] = '40eec1359c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('author_phone', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('source_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'source_title')
    op.drop_column('matches', 'author_phone')
    # ### end Alembic commands ###
